package com.key.tools.cookie.db.dao;

import com.key.tools.cookie.db.model.Cookie;

public interface CookieMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cookie
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cookie
     *
     * @mbggenerated
     */
    int insert(Cookie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cookie
     *
     * @mbggenerated
     */
    int insertSelective(Cookie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cookie
     *
     * @mbggenerated
     */
    Cookie selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cookie
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Cookie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cookie
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Cookie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cookie
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Cookie record);
}