package com.key.tools.stock.db.model;

import java.util.Date;

public class StockHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_history.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_history.stock_exchange
     *
     * @mbggenerated
     */
    private String stockExchange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_history.stock_code
     *
     * @mbggenerated
     */
    private String stockCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_history.date
     *
     * @mbggenerated
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_history.open
     *
     * @mbggenerated
     */
    private Double open;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_history.close
     *
     * @mbggenerated
     */
    private Double close;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_history.high
     *
     * @mbggenerated
     */
    private Double high;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_history.low
     *
     * @mbggenerated
     */
    private Double low;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_history.volume
     *
     * @mbggenerated
     */
    private Long volume;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_history.id
     *
     * @return the value of stock_history.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_history.id
     *
     * @param id the value for stock_history.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_history.stock_exchange
     *
     * @return the value of stock_history.stock_exchange
     *
     * @mbggenerated
     */
    public String getStockExchange() {
        return stockExchange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_history.stock_exchange
     *
     * @param stockExchange the value for stock_history.stock_exchange
     *
     * @mbggenerated
     */
    public void setStockExchange(String stockExchange) {
        this.stockExchange = stockExchange == null ? null : stockExchange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_history.stock_code
     *
     * @return the value of stock_history.stock_code
     *
     * @mbggenerated
     */
    public String getStockCode() {
        return stockCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_history.stock_code
     *
     * @param stockCode the value for stock_history.stock_code
     *
     * @mbggenerated
     */
    public void setStockCode(String stockCode) {
        this.stockCode = stockCode == null ? null : stockCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_history.date
     *
     * @return the value of stock_history.date
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_history.date
     *
     * @param date the value for stock_history.date
     *
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_history.open
     *
     * @return the value of stock_history.open
     *
     * @mbggenerated
     */
    public Double getOpen() {
        return open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_history.open
     *
     * @param open the value for stock_history.open
     *
     * @mbggenerated
     */
    public void setOpen(Double open) {
        this.open = open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_history.close
     *
     * @return the value of stock_history.close
     *
     * @mbggenerated
     */
    public Double getClose() {
        return close;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_history.close
     *
     * @param close the value for stock_history.close
     *
     * @mbggenerated
     */
    public void setClose(Double close) {
        this.close = close;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_history.high
     *
     * @return the value of stock_history.high
     *
     * @mbggenerated
     */
    public Double getHigh() {
        return high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_history.high
     *
     * @param high the value for stock_history.high
     *
     * @mbggenerated
     */
    public void setHigh(Double high) {
        this.high = high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_history.low
     *
     * @return the value of stock_history.low
     *
     * @mbggenerated
     */
    public Double getLow() {
        return low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_history.low
     *
     * @param low the value for stock_history.low
     *
     * @mbggenerated
     */
    public void setLow(Double low) {
        this.low = low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_history.volume
     *
     * @return the value of stock_history.volume
     *
     * @mbggenerated
     */
    public Long getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_history.volume
     *
     * @param volume the value for stock_history.volume
     *
     * @mbggenerated
     */
    public void setVolume(Long volume) {
        this.volume = volume;
    }
}