package com.key.tools.cookie.db.model;

import java.util.Date;

public class Cookie {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cookie.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cookie.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cookie.last_time
     *
     * @mbggenerated
     */
    private Date lastTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cookie.cookie
     *
     * @mbggenerated
     */
    private String cookie;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cookie.user_id
     *
     * @return the value of cookie.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cookie.user_id
     *
     * @param userId the value for cookie.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cookie.create_time
     *
     * @return the value of cookie.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cookie.create_time
     *
     * @param createTime the value for cookie.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cookie.last_time
     *
     * @return the value of cookie.last_time
     *
     * @mbggenerated
     */
    public Date getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cookie.last_time
     *
     * @param lastTime the value for cookie.last_time
     *
     * @mbggenerated
     */
    public void setLastTime(Date lastTime) {
        this.lastTime = lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cookie.cookie
     *
     * @return the value of cookie.cookie
     *
     * @mbggenerated
     */
    public String getCookie() {
        return cookie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cookie.cookie
     *
     * @param cookie the value for cookie.cookie
     *
     * @mbggenerated
     */
    public void setCookie(String cookie) {
        this.cookie = cookie == null ? null : cookie.trim();
    }
}