package com.key.tools.stock.db.dao;

import com.key.tools.stock.db.model.StockHistory;

public interface StockHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_history
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_history
     *
     * @mbggenerated
     */
    int insert(StockHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_history
     *
     * @mbggenerated
     */
    int insertSelective(StockHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_history
     *
     * @mbggenerated
     */
    StockHistory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_history
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StockHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_history
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StockHistory record);
}